trigger:
- master
- develop

pool:
  vmImage: 'macos-latest'

variables:
- group: AppiOS
- name: SDK
  value: 'iphoneos'


steps:

- bash: 'cp app/env-configs/prod.json app/settings.json'
  displayName: "Setting prod environment appsettings.json"

- task: UseNode@1
  displayName: 'Specifying Node version'

- bash: 'npm i'
  displayName: 'Installing JS dependencies with NPM'

- task: InstallAppleCertificate@2
  displayName: 'Install Apple certificate - dd.mm.2021'
  inputs:
    certSecureFile: 'statoil_desi.p12'
    certPwd: '$(p12Password)'

- task: InstallAppleProvisioningProfile@1
  displayName: 'Install Apple provisioning profile - 2021-02-03 - Prod'
  inputs:
    provProfileSecureFile: 'HearingTest_Prod.mobileprovision'


- task: Xcode@5
  inputs:
    actions: 'build'
    configuration: 'Release'
    xcWorkspacePath: 'ios/madapp.xcworkspace'
    scheme: 'madapp'
    xcodeVersion: '9'
    packageApp: true
    exportPath: '$(agent.builddirectory)/output/$(SDK)/$(BuildConfiguration)'
    signingOption: 'manual'
    signingIdentity: 'iPhone Distribution: Statoil ASA'
    provisioningProfileUuid: '26ce6540-bd16-4830-9dc9-ceb94f5a06a0'
    args: '-UseModernBuildSystem=NO'


- task: CopyFiles@2
  displayName: 'Copying our built files to: $(build.artifactstagingdirectory)/$(BuildConfiguration)'
  inputs:
    SourceFolder: '$(agent.builddirectory)/output/$(SDK)/$(BuildConfiguration)'
    Contents: '**/*.ipa'
    TargetFolder: '$(build.artifactstagingdirectory)/$(BuildConfiguration)'

- task: PublishBuildArtifacts@1
  displayName: 'Publishing the Artifact: drop'
