platform :ios, '9.0'

target 'madapp' do
  # Pods for madapp

  rn_path = '../node_modules/react-native'

  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga"
  pod 'React', path: rn_path
  #pod 'Folly', :podspec => "#{rn_path}/third-party-podspecs/Folly.podspec"
  #pod 'glog', :podspec => "#{rn_path}/third-party-podspecs/glog.podspec"
  #pod 'DoubleConversion', :podspec => "#{rn_path}/third-party-podspecs/DoubleConversion.podspec"

  pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'

  pod 'RNSound', :path => '../node_modules/react-native-sound'

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == "React"
        target.remove_from_project
      end
    end
  end

  pod 'ADAL', '~> 2.6.3'
  pod 'TrustKit', '1.4.2'
  #pod 'HockeySDK', '4.1.6', :subspecs => ['AllFeaturesLib']
  pod 'SDWebImage', '~>4.0'
  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

end

