@startuml

:Spill av test-lyd;

if (Kan du høre lyden?) then (Ja)
:Start hørselstest;
else (Nei)
:- Sjekk at telefonen ikke er i stille modus.\n- Trekk ut hodetelefonene og hør om musikken\n spilles gjennom høytalerne til telefonen.;
endif
:Hørselstest;
if(Jeg har behov for å stoppe testen) then (avbryt)
if(Avbryt test)
else

endif
note
Hva skjer med testen mens
"avbryt-test" modulen vises?

a. Den fortsetter i bakgrunnen.
  - Dette fører til upresise resultater.
b. Den settes på pause.
  - Hvorfor har vi ikke pause-funksjonalitet da?

Forslag til endring:
To-stegs knapp.

"Avbryt test" -(click)-> "Er du sikker?" -(click)-> The test is aborted.

endnote
@enduml
