name: Build and release to Prod 🚀

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release-please.outputs.release_created }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release-please
        with:
          release-type: expo

  trigger-build:
    if: ${{ needs.release-please.outputs.release_created}}
    needs: release-please
    secrets: inherit
    uses: equinor/hearing-test/.github/workflows/build-release-ios.yml@main
    with:
      environment: Prod