name: Build and release to Test 🧪

on:
    push:
        branches:
            - SWTest

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
    trigger-build:
        if:
            ${{ !startsWith(github.event.head_commit.message, 'docs')  && !startsWith(github.event.head_commit.message, 'style') && !startswith(github.event.head_commit.message, 'refactor') }}
        secrets: inherit
        uses: equinor/hearing-test/.github/workflows/build-release-ios.yml@SWTest
        with:
            environment: Test
