# Triggers
# Learn more https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&tabs=yaml
trigger:
  batch: true
  branches:
    include:
      - f/*
      - bf/*
    exclude:
      - master
      - develop

# no PR triggers
pr: none

pool:
  vmImage: 'macos-latest'

variables:
  - group: AppiOS
  - name: SDK
    value: 'iphoneos'
  - name: AppName
    value: 'hearingtest'
  - name: BuildConfiguration
    value: 'dev'
  - name: DisplayName
    value: 'Hørselstest Dev'


steps:

  - bash: 'cp app/env-configs/dev.json app/settings.json'
    displayName: "Setting dev environment > settings.json"

  - task: PlistPatch@3
    inputs:
      SyntaxType: 'slick'
      PlistWorkingDir: 'ios/madapp'
      PlistTargetFilters: 'Info.plist'
      PlistPatchContent: '= /CFBundleDisplayName => "$(DisplayName)"'
      OutputPatchFile: true
      FailIfNoPatchApplied: true
      TreatErrors: 'ERROR'

  - task: UseNode@1
    displayName: 'Specifying Node version'

  - bash: 'npm i'
    displayName: 'Installing JS dependencies with NPM'

  - task: InstallAppleCertificate@2
    displayName: 'Install Apple certificate - dd.mm.2021'
    inputs:
      certSecureFile: 'statoil_desi.p12'
      certPwd: '$(p12Password)'

  - task: InstallAppleProvisioningProfile@1
    displayName: 'Install Apple provisioning profile'
    inputs:
      provProfileSecureFile: 'HearingTest_Dev.mobileprovision'


  - task: Xcode@5
    inputs:
      xcWorkspacePath: 'ios/madapp.xcworkspace'
      scheme: 'madapp'
      xcodeVersion: '10'
      packageApp: true
      exportPath: '$(agent.builddirectory)/output/$(SDK)/$(BuildConfiguration)'
      signingOption: 'manual'
      signingIdentity: 'iPhone Distribution: Statoil ASA'
      provisioningProfileUuid: '983aa4f0-3bc2-4631-947a-a1c82bab92f5'
      args: 'PRODUCT_BUNDLE_IDENTIFIER=com.equinor.$(AppName).$(BuildConfiguration)'

  - task: CopyFiles@2
    displayName: 'Copying our built files to: $(build.artifactstagingdirectory)/$(BuildConfiguration)'
    inputs:
      SourceFolder: '$(agent.builddirectory)/output/$(SDK)/$(BuildConfiguration)'
      Contents: '**/*.ipa'
      TargetFolder: '$(build.artifactstagingdirectory)/$(BuildConfiguration)'

  - task: PublishBuildArtifacts@1
    displayName: 'Publishing the Artifact: drop'

  - bash: 'mv $(build.artifactstagingdirectory)/$(BuildConfiguration)/madapp.ipa $(build.artifactstagingdirectory)/$(BuildConfiguration)/$(appName)-$(BuildConfiguration).ipa'
    displayName: 'Rename app to $(appName)-$(BuildConfiguration)'


  - task: AppCenterDistribute@3
    inputs:
      serverEndpoint: 'AppCenter'
      appSlug: 'Statoil-ASA-Go-Digital/HearingTest-Dev'
      appFile: '$(build.artifactstagingdirectory)/$(BuildConfiguration)/$(appName)-$(BuildConfiguration).ipa'
      releaseNotesOption: 'input'
      releaseNotesInput: |
        New update!
        Please test it.
      destinationType: 'groups'
      distributionGroupId: 'ff26f77c-45ad-4af9-ba7c-b574e7161b65'
